server:
  host: epp.ote.nixiregistry.in
  port: 700

authentication:
  username: csc_egov_in_a
  password: 63053d90c4cdb9

tls:
  cert_file: certs/cert.pem
  key_file: certs/priv_key.key
  insecure_skip_verify: false
  ca_file: certs/ca.pem
timeout:
  connect: 10
  read: 30
  write: 30
